# Understanding N-Dimensional Arrays and Axes

Disclaimer: Written with excessive help from a following stack overflow thread on the same topic

#### AXIS MEANING
- axis = 0 
    
    - __along rows__ 
    - [ act on all rows in each column]
    - == axis ='index'
- axis = 1 
    - __along columns__ 
    - [ act on all columns in each row] 
    - axis ='columns'

#### UNDERSTANDING ND-ARRAYS

- Think of nd array with __shape(3,5,7)__

        - it is a 3D array 
        - the configuration looks like 
             - 3 slices of bread with each slice having dimensions 5 by 7
             
        - 1 st slice:
            - a[0,:,:]
            
        - 2 nd slice:
            - a[1,:,:]
            
        - 3 rd slice:
            - a[2,:,:]

In [2]:
import numpy as np

In [3]:
a = np.ones((3,5,7))

In [4]:
a

array([[[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]]])

In [5]:
a[0,:,:]

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [7]:
x0=np.sum(a,axis=0)
x0

array([[3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3.]])

In [8]:
x1=np.sum(a,axis=1)
x1

array([[5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5.]])

In [ ]:
x2=np.sum(a,axis=2)
x2