# Random Module in Python

Python uses Mersenne Twister algorithm, a pseudo-random generator (PRNG) to generate pseudo-random numbers.
Studies reveal that PRNGs are suitable for applications such as simulation and modeling but not recommended for cryptographic purposes

- __1. randint(a,b)__
- Get a random integer from numbers between a+1 till b (inclusive)

In [4]:
import random
print(random.randint(0,5))

3


- __2. random()__
- gives a very small float number 

In [5]:
print(random.random()) 

0.09594886746692055


In [6]:
print(random.random()*100) 

99.61076830469004


- __3. choice(LIST)__
- choose random element from sequence

In [10]:
print(random.choice([101,3,2,34,56,65,32]))

2


- __4. shuffle(sequence)__
- shufflesthe element of the sequence ,in-place in a random order

In [24]:
a=['p','a','r','u']
random.shuffle(a)
a

['p', 'u', 'r', 'a']

- __5. randrange(start,stop,step)__
- generate a randomly selected element from the given range

In [25]:
x = random.randrange(2,50,2)
x

40

In [34]:
for i in range(10):
    print(random.randrange(23,47))

25
27
33
27
34
36
42
28
31
45


- __6.sample(collection, random_list_length)__
- The sample() function randomly selects N items from a given collection (list, tuple, string, dictionary, set) and returns them as a list.
- It works by sampling the items without replacement. It means a single element from the sequence can appear in the resultant list at most once.

In [35]:
print(random.sample('parvathy', 4))

['v', 'h', 'a', 'p']


- __7. uniform() __
- It is an extension of the random() function. In this, you can specify the lower and upper bounds to generate a random number other than the ones between 0 and 1.

In [36]:
print(random.uniform(23,67))

64.72985983432774


### Example
There are only two outcomes allowed, so rather than use numbers and convert them,
the words “heads” and “tails” are used with choice(). 

The results are tabulated in a dictionary using the outcome names as keys.

In [31]:
import random

outcomes = {'heads':0, 
            'tails':0,
           }

sides = list(outcomes.keys())

for i in range(10000):
    outcomes[random.choice(sides)]+=1
    
print('Heads :', outcomes['heads'])
print('Tails :', outcomes['tails'])

Heads : 4971
Tails : 5029


### Advanced distributions

<img src="f2.png">

# Random Sampling in Numpy

https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.random.rand.html#numpy.random.rand

In [1]:
import numpy as np

#### np.random.rand
- Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)

In [2]:
np.random.rand()

0.1434924924932539

In [3]:
np.random.rand(2,5)

array([[0.57474201, 0.17582812, 0.90606352, 0.61667389, 0.72403494],
       [0.27651549, 0.08399775, 0.4104976 , 0.46491292, 0.45315696]])

In [4]:
np.random.rand(2,2,5)

array([[[0.73103142, 0.27078408, 0.7960099 , 0.43647278, 0.70725853],
        [0.31204273, 0.49352264, 0.31245044, 0.79760162, 0.99439608]],

       [[0.49323401, 0.99065723, 0.51711174, 0.75530436, 0.3904735 ],
        [0.44012854, 0.30355245, 0.49987322, 0.913018  , 0.23161183]]])

In [7]:
np.random.rand(2,2,5,1)

array([[[[0.21833357],
         [0.41992971],
         [0.44813068],
         [0.59856707],
         [0.55322594]],

        [[0.36244556],
         [0.04190595],
         [0.67302156],
         [0.19682962],
         [0.20783529]]],


       [[[0.90871874],
         [0.04295153],
         [0.00270766],
         [0.66639798],
         [0.76062798]],

        [[0.19639427],
         [0.48500801],
         [0.16409439],
         [0.75174112],
         [0.7691794 ]]]])

#### np.random.randn

- Return a sample (or samples) from the “standard normal” distribution.

If positive, int_like or int-convertible arguments are provided, randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.

- For random samples from N(mu, sigma^2), use:

sigma * np.random.randn(...) + mu

In [8]:
np.random.randn()

-1.5154298237774726

In [10]:
# Two-by-four array of samples from N(3, 6.25):
2.5 * np.random.randn(2,4)+ 3

array([[ 1.90314441,  7.56308471,  5.60256818,  2.26803762],
       [ 3.09555513,  2.40023548, -0.36124694, -0.19131126]])